FROM mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
# 挂上宿主机代理
# ENV http_proxy=http://192.168.1.3:7890
# ENV https_proxy=https://192.168.1.3:7890
# ENV no_proxy='.huaweicloud.com,.io.plus,.inner,.cn,.svc,.local,localhost,127.0.0.1'


# COPY  .devcontainer/install_env.sh  .

# COPY . /app/
RUN echo "deb https://mirrors.hust.edu.cn/debian bookworm main contrib non-free" > /etc/apt/sources.list && \
    echo "deb https://mirrors.hust.edu.cn/debian bookworm-updates main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb https://mirrors.hust.edu.cn/debian-security bookworm-security main contrib non-free" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        bash \
        vim \
        sqlite3 \
        dnsutils \
        git \
        openssh-server \
        openssh-client \
        curl \
    && rm -rf /var/lib/apt/lists/*
# RUN yarn install
RUN pnpm config set registry http://mirrors.cloud.tencent.com/npm/

# RUN sh ./install_env.sh
